/**
 * ghl-notify.js — Send data back to GHL after pages are generated
 * Updates the contact record and optionally triggers a GHL workflow
 *
 * SETUP: Set env vars: GHL_API_KEY, GHL_LOCATION_ID
 */

const axios = require("axios");

const GHL_API_KEY     = process.env.GHL_API_KEY;
const GHL_LOCATION_ID = process.env.GHL_LOCATION_ID;
const GHL_BASE_URL    = "https://services.leadconnectorhq.com";

const headers = {
  Authorization: `Bearer ${GHL_API_KEY}`,
  "Content-Type": "application/json",
  Version: "2021-07-28",
};

/**
 * Update a GHL contact with the generated landing page URL
 * This lets you see the page URL right in the contact record
 */
async function updateContactWithPageUrl(contactId, pageUrl, privacyUrl, termsUrl) {
  try {
    await axios.put(
      `${GHL_BASE_URL}/contacts/${contactId}`,
      {
        customFields: [
          { key: "landing_page_url",    field_value: pageUrl    },
          { key: "privacy_policy_url",  field_value: privacyUrl },
          { key: "sms_terms_url",       field_value: termsUrl   },
          { key: "a2p_pages_generated", field_value: "Yes"      },
          { key: "pages_generated_at",  field_value: new Date().toISOString() },
        ],
      },
      { headers }
    );
    console.log(`✅ GHL contact ${contactId} updated with page URLs`);
  } catch (err) {
    console.error("GHL update error:", err.response?.data || err.message);
  }
}

/**
 * Trigger a GHL workflow to notify the client
 * e.g., send them an SMS/email with their new landing page link
 */
async function triggerGHLWorkflow(contactId, workflowId) {
  try {
    await axios.post(
      `${GHL_BASE_URL}/contacts/${contactId}/workflow/${workflowId}`,
      {},
      { headers }
    );
    console.log(`✅ GHL workflow ${workflowId} triggered for contact ${contactId}`);
  } catch (err) {
    console.error("GHL workflow trigger error:", err.response?.data || err.message);
  }
}

/**
 * Add a note to the contact's record in GHL
 */
async function addContactNote(contactId, pageUrl) {
  try {
    await axios.post(
      `${GHL_BASE_URL}/contacts/${contactId}/notes`,
      {
        body: `🚀 A2P Landing pages auto-generated!\n\nLanding Page: ${pageUrl}\nPrivacy Policy: ${pageUrl.replace("index.html","privacy-policy.html")}\nSMS Terms: ${pageUrl.replace("index.html","terms.html")}\n\nGenerated by A2P Agent on ${new Date().toLocaleString()}`,
        userId: "system",
      },
      { headers }
    );
    console.log(`📝 Note added to GHL contact ${contactId}`);
  } catch (err) {
    console.error("GHL note error:", err.response?.data || err.message);
  }
}

module.exports = { updateContactWithPageUrl, triggerGHLWorkflow, addContactNote };
